services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - MODEL_NAME=Production-model
      - GIT_PYTHON_REFRESH=quiet
  ui:
    build:
      context: .
      dockerfile: src/ui/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - model_url=http://api:8000/predict
      
  
