services:
  fastapi:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - MODEL_NAME=Production-model
      - GIT_PYTHON_REFRESH=quiet
  interface:
    build:
      context: .
      dockerfile: src/interface/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - model_url=http://fastapi:8000/predict
      
  
